CREATE TABLE PACIENTES (
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
GENERO CHAR(1) NOT NULL,
ESTADO_CIVIL VARCHAR(20) NOT NULL,

LOGRADOURO VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
CEP VARCHAR(20) NOT NULL,
COMPLEMENTO VARCHAR(100),
NUMERO VARCHAR(20) NOT NULL,
UF CHAR(2) NOT NULL,
CIDADE VARCHAR(100) NOT NULL
);